# Generated by Django 3.2.16 on 2026-08-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Полное название мороженого', max_length=200, verbose_name='Название')),
                ('description', models.TextField(help_text='Краткое описание вкуса или особенности', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена в рублях', max_digits=8, verbose_name='Цена (руб)')),
                ('weight', models.PositiveIntegerField(help_text='Вес порции в граммах (целое число)', verbose_name='Вес (грамм)')),
                ('calories', models.PositiveIntegerField(help_text='Количество килокалорий', verbose_name='Калорийность (ккал)')),
                ('protein', models.DecimalField(decimal_places=2, help_text='Содержание белков в граммах', max_digits=5, verbose_name='Белки (г)')),
                ('fat', models.DecimalField(decimal_places=2, help_text='Содержание жиров в граммах', max_digits=5, verbose_name='Жиры (г)')),
                ('carbs', models.DecimalField(decimal_places=2, help_text='Содержание углеводов в граммах', max_digits=5, verbose_name='Углеводы (г)')),
                ('image', models.ImageField(blank=True, help_text='Путь к файлу изображения продукта', null=True, upload_to='ice_creams/', verbose_name='Изображение')),
                ('is_available', models.BooleanField(default=True, help_text='Отображать ли товар на сайте', verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается при создании', verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Мороженое',
                'verbose_name_plural': 'Мороженое',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальное название, например, "Сливки (70%)"', max_length=100, unique=True, verbose_name='Название ингредиента')),
                ('ice_creams', models.ManyToManyField(help_text='Выберите виды мороженого, содержащие этот ингредиент', related_name='ingredients', to='ice_cream.IceCream', verbose_name='Мороженое')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name'],
            },
        ),
    ]
