# Generated by Django 3.2.16 on 2026-08-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='ice_creams',
        ),
        migrations.AddField(
            model_name='icecream',
            name='ingredients',
            field=models.ManyToManyField(blank=True, help_text='Выберите ингредиенты, входящие в состав', related_name='ice_creams', to='ice_cream.Ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Цена в рублях, например, 89.00', max_digits=8, verbose_name='Цена (руб)'),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='title',
            field=models.CharField(help_text='Полное название мороженого (например, "Сырное мороженое")', max_length=200, verbose_name='Название'),
        ),
    ]
